theme: jekyll-theme-cayman
github:
  is_project_page: false
description: A glance at the how energy consumption and production has changed over the last 2 decades and its impact
Aparna Shree Sivanandam, Daanish Mohammed, Sahithi Mattapalli and Kartik Sharma
